apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
spec:
    maxReplicas: {{ .Values.autoscale.max }}
    minReplicas: {{ .Values.autoscale.min }}
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: {{ .Values.name }}
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscale.cpu.targetAverageUtilization }}
---
