{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
{{- if .Values.namespace.labels }}
  labels:
{{ toYaml .Values.namespace.labels | indent 4 }}
{{- end -}}
{{- end -}}
