apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: {{ .Values.repoServer.replicas }}
  selector:
    matchLabels:
      app: argocd-repo-server
  template:
    metadata:
      labels:
        app: argocd-repo-server
    spec:
      automountServiceAccountToken: false
      containers:
      - name: argocd-repo-server
        image: argoproj/argocd:{{ .Values.image.tag }}
        imagePullPolicy: Always
        command: [argocd-repo-server]
        ports:
        - containerPort: 8081
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- if .Values.repoServer.resources  }}  
        resources:
{{ toYaml .Values.repoServer.resources | indent 10 }}
        {{- end }}