apiVersion: v1
kind: Service
metadata:
  name: argocd-server
{{- if .Values.server.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.server.service.annotations }}
    {{ $key }}: {{ tpl $value $ }}
  {{- end }}
{{- end }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  selector:
    app: argocd-server
  type: {{ default "ClusterIP" .Values.server.service.type }}
