{{- range $v, $spec := .Values.global.versions }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Values.global.name }}-{{ $v }}"
  labels:
    app: {{ $.Values.global.name | quote }}
    version: {{ $v | quote }}
spec:
  selector:
    matchLabels:
      app: {{ $.Values.global.name | quote }}
      version: {{ $v | quote }}
  template:
    metadata:
      labels:
        app: {{ $.Values.global.name | quote }}
        version: {{ $v }}
      {{- if $spec.podAnnotations }}
      annotations:
{{ toYaml $spec.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ $.Values.global.name | quote }}
          image: "{{ $spec.image.repository }}:{{ $spec.image.tag }}"
          {{- if $spec.args }}
          args:
{{ toYaml $spec.args | indent 12 }}
          {{- end }}
          imagePullPolicy: {{ $spec.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: applicationport
              containerPort: {{ $.Values.global.targetPort }}
              protocol: TCP
          {{- if $spec.livenessProbe }}
          livenessProbe:
{{ toYaml $spec.livenessProbe | indent 12 }}
          {{- end }}
          {{- if $spec.readinessProbe }}
          readinessProbe:
{{ toYaml $spec.readinessProbe | indent 12 }}
          {{- end }}
          env:
          {{- if $spec.env }}
{{ toYaml $spec.env | indent 12 -}}
          {{- end }}
            - name: JAEGER_AGENT_HOST
              value: {{ $.Values.global.tracingServiceHost | quote }}
{{- end }}
