
{{- range $service, $spec := .Values.global.externalServices}}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{$.Values.global.name}}.{{ $service }}-ext
spec:
  hosts:
  - {{ $spec.host | quote }}
  ports:
    - number: {{ $spec.port.number }}
      name: {{ $spec.port.name | quote }}
      protocol: {{ $spec.port.protocol | quote }}
  resolution: DNS
  location: MESH_EXTERNAL
{{- if eq $spec.port.protocol "HTTPS" }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{$.Values.global.name}}.{{ $service }}-ext"
spec:
  hosts:
  - {{ $spec.host | quote }}
  tls:
  - match:
    - port: {{ $spec.port.number }}
      sni_hosts:
      - {{ $spec.host | quote }}
    route:
    - destination:
        host: {{ $spec.host | quote }}
        port:
          number: {{ $spec.port.number }}
      weight: 100
{{- end }}
{{- end }}
