global:
  istioNamespace: istio-system
  dnsDomain: 
  tracingAddress: 

  customGateways: 
    # - name: # Name of the ingress gateway
    #   namespace: # Namespace of the ingress gateway
    #   serviceAnnotations: {} # Custom annotations for the gateway
    #   labels: {}
    #   ports: {}