{{- range $spec := .Values.gateways }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ $spec.name }}
    namespace: {{ $spec.namespace }}
spec:
    maxReplicas: {{ $spec.autoscale.max }}
    minReplicas: {{ $spec.autoscale.min }}
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: {{ $spec.name }}
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $spec.autoscale.cpu.targetAverageUtilization }}
---
{{- end }}