{{- range $spec := .Values.global.customGateways }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ $spec.name }}
    namespace: {{ $spec.namespace }}
spec:
    maxReplicas: 5
    minReplicas: 2
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: {{ $spec.name }}
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
{{- end }}