{{- range $customGateway := .Values.global.customGateways }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: "istio-gateway-{{ $customGateway.name }}"
  name: {{ $customGateway.name | quote }}
rules:
- apiGroups: ["extensions"]
  resources: ["thirdpartyresources", "virtualservices", "destinationrules", "gateways"]
  verbs: ["get", "watch", "list", "update"]
---
{{- end }}
