{{- range $spec := .Values.global.customGateways }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $spec.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $spec.hostPrefix }}.{{ $.Values.dnsDomain }}
    {{- range $key, $val := $spec.serviceAnnotations }}
    {{ $key }}: {{ $val }}
    {{- end }}
  labels:
    {{- range $key, $val := $spec.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  type: LoadBalancer
  selector:
    {{- range $key, $val := $spec.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
  ports:
    {{- range $key, $val := $spec.ports }}
    -
      {{- range $pkey, $pval := $val }}
      {{ $pkey}}: {{ $pval }}
      {{- end }}
    {{- end }}
---
{{- end }}
