---
apiVersion: v1
kind: Service
metadata:
  name: kiam-server
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: kiam
    role: server
  ports:
  - name: grpc
    port: 443
    targetPort: 443
    protocol: TCP
